# Generated by Django 5.0.3 on 2024-05-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tataapp', '0002_alter_newcars_image_alter_newcars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
