# Generated by Django 5.0.3 on 2024-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tataapp', '0003_featuredcars'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
