# Generated by Django 5.0.3 on 2024-05-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tataapp', '0004_welcomehero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='welcomeHero',
        ),
    ]
